# Copyright (C) 2026 Philipp Bätz
#
# This file is part of LabCIRS.
#
# LabCIRS is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# LabCIRS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with LabCIRS.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 4.2.20 on 2026-09-30 10:59

from django.db import migrations

# Tables of the removed django-registration-redux app. Existing installations still have them,
# and their foreign keys to auth_user would block the deletion of users.
TABLES = ('registration_supervisedregistrationprofile', 'registration_registrationprofile')


def drop_tables(apps, schema_editor):
    cascade = ' CASCADE' if schema_editor.connection.vendor == 'postgresql' else ''
    for table in TABLES:
        schema_editor.execute(f'DROP TABLE IF EXISTS {table}{cascade}')


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0001_squashed_0019_reinitialized'),
    ]

    operations = [
        migrations.RunPython(drop_tables, migrations.RunPython.noop),
    ]
