# Copyright (C) 2026 Philipp Bätz
#
# This file is part of LabCIRS.
#
# LabCIRS is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# LabCIRS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with LabCIRS.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.17 on 2026-09-30 11:18

# django-parler 2.4 replaced unique_together on translation models with a UniqueConstraint.
# notification_recipients lost null=True, which had no effect on a ManyToManyField (fields.W340).

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0020_drop_registration_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labcirsconfigtranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='publishableincidenttranslation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='labcirsconfig',
            name='notification_recipients',
            field=models.ManyToManyField(blank=True, help_text='Choose recipients of the notification email', to=settings.AUTH_USER_MODEL, verbose_name='Notification recipients'),
        ),
        migrations.AddConstraint(
            model_name='labcirsconfigtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='cirs_labcirsconfig_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='publishableincidenttranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='cirs_publishableincident_translation_uniq_lang'),
        ),
    ]
