# Copyright (C) 2026 Philipp Bätz
#
# This file is part of LabCIRS.
#
# LabCIRS is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# LabCIRS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with LabCIRS.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.17 on 2026-10-01 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0025_remove_registration_content_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('in process', 'in process'), ('under supervision', 'under supervision'), ('completed', 'completed')], max_length=255, verbose_name='Status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Changed at')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='cirs.criticalincident', verbose_name='Critical incident')),
            ],
            options={
                'verbose_name': 'Status change',
                'verbose_name_plural': 'Status changes',
                'ordering': ['changed_at'],
            },
        ),
    ]
