# Copyright (C) 2026 Philipp Bätz
#
# This file is part of LabCIRS.
#
# LabCIRS is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# LabCIRS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with LabCIRS.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 5.2.17 on 2026-10-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cirs', '0026_incidentstatuschange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentstatuschange',
            options={'ordering': ['changed_at', 'id'], 'verbose_name': 'Status change', 'verbose_name_plural': 'Status changes'},
        ),
    ]
